# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-26 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20160626_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anexo',
            name='estado',
        ),
        migrations.AddField(
            model_name='requisito',
            name='estado',
            field=models.CharField(choices=[('FISICO', 'FÍSICO'), ('VIRTUAL', 'VIRTUAL')], default='FISICO', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'NUEVO'), ('PERDIDO', 'PERDIDO'), ('MOVIMIENTO', 'EN MOVIMIENTO'), ('FINALIZADO', 'FINALIZADO')], max_length=25),
        ),
    ]
