# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20160626_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='documento',
            field=models.FileField(upload_to='documentos'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='anexos',
            field=models.ManyToManyField(blank=True, null=True, related_name='anexos', to='webapp.Anexo'),
        ),
    ]
