# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20160629_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramite',
            name='anexos',
        ),
        migrations.AddField(
            model_name='tramite',
            name='hoja_de_ruta',
            field=models.ManyToManyField(related_name='oficinas', to='webapp.Oficina'),
        ),
        migrations.AddField(
            model_name='usuariotramite',
            name='anexos',
            field=models.ManyToManyField(blank=True, null=True, related_name='anexos', to='webapp.Anexo'),
        ),
    ]
