# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-24 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20160707_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('campo1', models.CharField(max_length=10)),
                ('campo2', models.CharField(max_length=10)),
                ('campo3', models.CharField(max_length=10)),
                ('campo4', models.CharField(max_length=10)),
                ('campo5', models.CharField(max_length=10)),
                ('campo6', models.CharField(max_length=10)),
                ('campo7', models.CharField(max_length=10)),
                ('campo8', models.CharField(max_length=10)),
                ('campo9', models.CharField(max_length=10)),
                ('codigo', models.CharField(default=webapp.models.fut_code, max_length=8)),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fut', to='webapp.Tramite')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fut', to='webapp.Solicitante')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
