# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-24 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_fut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitante',
            name='solicitante_codigo',
            field=models.CharField(default=webapp.models.solicitante_code, max_length=10),
        ),
    ]
