# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-03 02:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20161124_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fut',
            name='tramite',
        ),
        migrations.RemoveField(
            model_name='fut',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Fut',
        ),
    ]
