# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-13 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20161202_2129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movimiento',
        ),
    ]
