# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-26 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_delete_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariotramite',
            name='codigo',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='hoja_de_ruta',
            field=models.ManyToManyField(blank=True, null=True, related_name='oficinas', to='webapp.Oficina'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='requisitos',
            field=models.ManyToManyField(blank=True, null=True, related_name='requisitos', to='webapp.Requisito'),
        ),
    ]
