# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-28 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20170227_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariotramite',
            name='estado',
            field=models.CharField(blank=True, choices=[('NUEVO', 'NUEVO'), ('PERDIDO', 'PERDIDO'), ('EN MOVIMIENTO', 'EN MOVIMIENTO'), ('FINALIZADO', 'FINALIZADO'), ('CANCELADO', 'CANCELADO')], default='NUEVO', max_length=25, null=True),
        ),
    ]
