# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-03 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20170227_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='jefe_tramite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramite', to='webapp.JefeDeTramite'),
        ),
    ]
